# -*- coding: utf-8 -*-
"""MineColabReloaded.ipynb

Automatically generated by Colab.

```
 /$$      /$$ /$$                      /$$$$$$            /$$           /$$      
| $$$    /$$$|__/                     /$$__  $$          | $$          | $$      
| $$$$  /$$$$ /$$ /$$$$$$$   /$$$$$$ | $$  \__/  /$$$$$$ | $$  /$$$$$$ | $$$$$$$
| $$ $$/$$ $$| $$| $$__  $$ /$$__  $$| $$       /$$__  $$| $$ |____  $$| $$__  $$
| $$  $$$| $$| $$| $$  \ $$| $$$$$$$$| $$      | $$  \ $$| $$  /$$$$$$$| $$  \ $$
| $$\  $ | $$| $$| $$  | $$| $$_____/| $$    $$| $$  | $$| $$ /$$__  $$| $$  | $$
| $$ \/  | $$| $$| $$  | $$|  $$$$$$$|  $$$$$$/|  $$$$$$/| $$|  $$$$$$$| $$$$$$$/
|__/     |__/|__/|__/  |__/ \_______/ \______/  \______/ |__/ \_______/|
 /$$$$$$$  /$$$$$$$$ /$$        /$$$$$$   /$$$$$$  /$$$$$$$  /$$$$$$$$ /$$$$$$$
| $$__  $$| $$_____/| $$       /$$__  $$ /$$__  $$| $$__  $$| $$_____/| $$__  $$
| $$  \ $$| $$      | $$      | $$  \ $$| $$  \ $$| $$  \ $$| $$      | $$  \ $$
| $$$$$$$/| $$$$$   | $$      | $$  | $$| $$$$$$$$| $$  | $$| $$$$$   | $$  | $$
| $$__  $$| $$__/   | $$      | $$  | $$| $$__  $$| $$  | $$| $$__/   | $$  | $$
| $$  \ $$| $$      | $$      | $$  | $$| $$  | $$| $$  | $$| $$      | $$  | $$
| $$  | $$| $$$$$$$$| $$$$$$$$|  $$$$$$/| $$  | $$| $$$$$$$/| $$$$$$$$| $$$$$$$/
|__/  |__/|________/|________/ \______/ |__/  |__/|_______/ |________/|_______/
```
**Crea un Servidor de Minecraft en Google Colab!**

---

El Script original fue creado por thecoder-001, pero el usuario SoyMichas tradujo la mayoria al español y lo actualizo. Esta es la version completamente traducida y con PurpurMC disponible!

Original: https://github.com/thecoder-001/MineColab

# **1º Paso -> Crear-el-servidor (Solo hacer la primera vez)**

El codigo de abajo creará tu servidor y aceptará el EULA de Minecraft. Luego de completar este paso, tu servidor estará listo para iniciarse.

**Descargar el Servidor de Minecraft**

El codigo de abajo descargará PurpurMC en la version 1.21 (puedes cambiarlo), un tipo de servidor paper de alto rendimiento el cual permite utilizar plugins.

- Los archivos del servidor estarán guardados en tu Google Drive (Los de la cuenta de Google que elijas o estes usando)
"""

# Commented out IPython magic to ensure Python compatibility.
# Cambia '1.21' con la version que desees.
# Versiones disponibles:
# - 1.21
# - 1.20
# - 1.19
# - 1.18
# - 1.17
# - 1.16
# - 1.15
# - 1.14
# - 1.13
# - 1.12
# - 1.11
# - 1.10
# - 1.9
# - 1.8
# Las nuevas versiones tambien deberían funcionar, pero no esta 100% garantizado.
version = '1.21'

# Elige el tipo de servidor (software). Estos son los que estan disponibles:
# - vanilla (Minecraft Vanilla sin mods ni plugins)
# - forge (Te permite jugar con MODS) [Aviso: la instalación tarda APROX 10-15 min, al ejecutar el primer paso, esperar a que ponga COMPLETADO]
# - fabric (Es una alternativa a Forge)
# - paper (Te permite jugar con plugins. Es lo mismo que Spiggot, Bukkit, etc.)
# - purpur (Es una version mejorada de paper. Posee una gran optimizacion y compatibilidad con plugins)

server_type = 'purpur'  # Tipo de servidor (software)

# En caso de que uses FORGE (OBLIGATORIO):
forge_version = "51.0.30"

from google.colab import drive
import requests
import json
import os

# Monta Google Drive en Colab para almacenar el servidor de Minecraft (Es necesario dar acceso a tu cuenta de Google)
drive.mount('/content/drive')

# Preguntar el nombre del servidor
server_name = input('Nombre del servidor: ')
server_route = f"/content/drive/My Drive/{server_name}/"

# Crea la carpeta donde se almacenaran los archivos del servidor
if not os.path.exists(server_route):
    os.makedirs(server_route)  # Crea la carpeta si no existe
# %cd {server_route}

# Descarga automáticamente el .jar dependiendo del servidor elegido
if server_type == 'paper':
    a = requests.get(f"https://api.papermc.io/v2/projects/paper/versions/{version}")
    b = requests.get(f"https://api.papermc.io/v2/projects/paper/versions/{version}/builds/{a.json()['builds'][-1]}")
    print(f"https://api.papermc.io/v2/projects/paper/versions/{version}/builds/{a.json()['builds'][-1]}/downloads/{b.json()['downloads']['application']['name']}")
    serverURL = f"https://api.papermc.io/v2/projects/paper/versions/{version}/builds/{a.json()['builds'][-1]}/downloads/{b.json()['downloads']['application']['name']}"

if server_type == 'forge':
    serverURL = f"https://maven.minecraftforge.net/net/minecraftforge/forge/{version}-{forge_version}/forge-{version}-{forge_version}-installer.jar"

if server_type == 'vanilla':
    serverURL = f"https://mcutils.com/api/server-jars/vanilla/{version}/download"

if server_type == 'fabric':
    serverURL = 'https://maven.fabricmc.net/net/fabricmc/fabric-installer/1.0.1/fabric-installer-1.0.1.jar'

if server_type == 'purpur':
    serverURL = f'https://api.purpurmc.org/v2/purpur/{version}/latest/download'

jar_name = {
    'paper': 'server.jar',
    'fabric': 'fabric-installer.jar',
    'forge': 'forge.jar',
    'purpur': 'purpur.jar',
    'vanilla': 'vanilla.jar'
}

print('Descargando a Google Drive...')

# Descarga del .jar del servidor
r = requests.get(serverURL)

if r.status_code == 200:
    with open(f'{server_route}{jar_name[server_type]}', 'wb') as f:
        f.write(r.content)
else:
    print(f'Error {r.status_code}. La versión que has elegido probablemente no funciona. Intenta de nuevo.')

if server_type == 'fabric':
    !java -jar fabric-installer.jar server -mcversion {version} -downloadMinecraft

if server_type == 'forge':
#     %cd {server_route}
    !java -jar forge.jar --installServer

# Guardar configuración en un archivo JSON
colabconfig = {
    "server_type": server_type,
    "server_version": version
}
json.dump(colabconfig, open("colabconfig.json", 'w'))

# Acepta el eula de Minecraft (OBLIGATORIO)
# %cd {server_route}
!echo "eula=true" >> eula.txt

print("SERVIDOR CREADO CON EXITO")

"""# **2° Paso -> Iniciar-el-servidor**

La celda de abajo iniciara el servidor ya creado, es importante que proporciones el nombre correcto del servidor a iniciar.
Pudes usar Ngrok o playit, la forma mas sencilla (y predeterminada) es usar playit, pero la IP cambiara cada cierto tiempo.

**SI USAS PLAYIT.GG:**
Cuando se este iniciando el servidor te dara un link con el cual añadiras un agente a tu cuenta de playit.gg y luego un tunnel (de tipo Minecraft Java). Una vez habilitado el tunnel, tendras la IP del servidor (algo-aleatorio.gl.joinmc.link).
"""

import os
import re
import json
import glob

# Actualiza el apt y muestra un mensaje según el resultado
!sudo apt update &>/dev/null && echo "Cache de apt actualizada con éxito" || echo "Falló la actualización de la cache de apt, es posible que recibas paquetes desactualizados"

server_name = input('Nombre del servidor a iniciar: ')
server_route = f"/content/drive/My Drive/{server_name}/"

from google.colab import drive
drive.mount('/content/drive')

# Concatenar correctamente el nombre del servidor
os.chdir(server_route)
!ls

# Cargar o crear el archivo de configuración
if os.path.isfile("colabconfig.json"):
        colabconfig = json.load(open("colabconfig.json"))
else:
    colabconfig = {"server_type": server_type, "server_version": version}
    json.dump(colabconfig, open("colabconfig.json",'w'))

version = colabconfig["server_version"]

# Instalar la versión adecuada de OpenJDK dependiendo de la versión del servidor
if colabconfig["server_version"] < "1.17":
    !sudo apt-get purge openjdk* > /dev/null 2>&1
    !sudo apt-get install openjdk-8-jre-headless &>/dev/null && echo "¡Yay! Openjdk8 instalado con éxito." || echo "Falló la instalación de OpenJdk8."
elif colabconfig["server_version"] >= "1.20.5":
    !sudo apt-get purge openjdk* > /dev/null 2>&1
    !sudo apt-get install openjdk-21-jre-headless &>/dev/null && echo "¡Yay! Openjdk21 instalado con éxito." || echo "Falló la instalación de OpenJdk21."
else:
    !sudo apt-get purge openjdk* > /dev/null 2>&1
    !sudo apt-get install openjdk-17-jre-headless &>/dev/null && echo "¡Yay! Openjdk17 instalado con éxito." || echo "Falló la instalación de OpenJdk17."

# Verificación de la versión de Java
java_ver = !java -version 2>&1 | awk -F[\"\.] -v OFS=. 'NR==1{print $2}'
if java_ver[0] == "17":
    print("Se está utilizando JAVA 17.")
elif java_ver[0] == "21":
    print("Se está utilizando JAVA 21.")
else:
    print("Estás utilizando una versión inferior a JAVA 17: ", java_ver[0], ". Esta versión de Java puede no ser compatible con Minecraft 1.17+")

# Selección de la lista de archivos .jar según el tipo de servidor
jar_list = {'paper': 'server.jar', 'purpur': 'purpur.jar', 'fabric': 'fabric-server-launch.jar', 'generic': 'server.jar', 'forge': 'forge.jar', 'vanilla': 'vanilla.jar', 'snapshot': 'snapshot.jar', 'mohist': 'mohist.jar'}
jar_name = jar_list.get(colabconfig["server_type"], "server.jar")

# Configuración de los flags para el servidor, dependiendo del tipo de servidor elegido
if colabconfig["server_type"] == "paper":
    server_flags = "-XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true"
else:
    server_flags = ""
memory_allocation = "-Xms8704M -Xmx8704M"

# Selección del servicio de túneles que deseas usar
tunnel_service = "playit"  # Si prefieres usar NGROK, cámbialo aquí <--------
print("Usando", tunnel_service)

# Configuración para ngrok
if tunnel_service == "ngrok":
    !pip -q install pyngrok
    from pyngrok import conf, ngrok

    print("Consigue tu authtoken de https://dashboard.ngrok.com/auth")
    import getpass

    authtoken = ""  # <---- TOKEN NGROK (PON AQUÍ TU TOKEN [TIENE QUE ESTAR ENTRE LAS "COMILLAS"])

    ! ngrok authtoken $authtoken # login en ngrok

    # Establece la región por defecto de ngrok
    conf.get_default().region = 'us'  # Cambia esto por la región que quieras

    # Conéctate a ngrok
    url = ngrok.connect(25565, 'tcp')
    print('La IP de tu servidor es ' + ((str(url).split('"')[1::2])[0]).replace('tcp://', ''))

# Configuración para playit
elif tunnel_service == "playit":
    ! curl -SsL https://playit-cloud.github.io/ppa/key.gpg | sudo apt-key add -
    ! sudo curl -SsL -o /etc/apt/sources.list.d/playit-cloud.list https://playit-cloud.github.io/ppa/playit-cloud.list
    print('Iniciando servidor...')
    ! sudo apt update &>/dev/null && sudo apt install playit &>/dev/null && echo "Playit.gg instalado" || echo "Error al instalar playit"
    if colabconfig["server_type"] == "forge":
        version = colabconfig["server_version"]
        if colabconfig["server_version"] < "1.17":
            oldpathtoforge = glob.glob("/content/drive/My Drive/" + server_name + f"/forge-{version}-*.jar")
            if oldpathtoforge:  # Verifica si la lista no está vacía
                path = oldpathtoforge[0]  # Obtiene el primer camino de la lista
                print(path)
                ! playit & java $memory_allocation -jar "{path}" nogui
            else:
                print("No se encontró el archivo forge universal jar.")
        else:
            pathtoforge = glob.glob("/content/drive/My Drive/" + server_name + f"/libraries/net/minecraftforge/forge/{version}-*/unix_*.txt")
            if pathtoforge:  # Verifica si la lista no está vacía
                path = pathtoforge[0]  # Obtiene el primer camino de la lista
                print(path)
                ! playit & java @user_jvm_args.txt "@{path}" "$@"
            else:
                print("No se encontró unix_args.txt.")
    else:
        ! playit & java $memory_allocation $server_flags -jar $jar_name nogui

print('Iniciando servidor...')

# Lanza el servidor dependiendo de la configuración de Forge
if colabconfig["server_type"] == "forge":
    version = colabconfig["server_version"]
    if colabconfig["server_version"] < "1.17":
        oldpathtoforge = glob.glob("/content/drive/My Drive/" + server_name + f"/forge-{version}-*.jar")
        if oldpathtoforge:  # Verifica si la lista no está vacía
            path = oldpathtoforge[0]  # Obtiene el primer camino de la lista
            print(path)
            !java $memory_allocation -jar "{path}" nogui
        else:
            print("No se encontró el archivo forge universal jar.")
    else:
        pathtoforge = glob.glob("/content/drive/My Drive/" + server_name + f"/libraries/net/minecraftforge/forge/{version}-*/unix_*.txt")
        if pathtoforge:  # Verifica si la lista no está vacía
            path = pathtoforge[0]  # Obtiene el primer camino de la lista
            print(path)
            !java @user_jvm_args.txt "@{path}" "$@"
        else:
            print("No se encontró unix_args.txt.")
else:
    !java $memory_allocation $server_flags -jar $jar_name nogui
